apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: aaf-master-bank
  labels:
    strimzi.io/cluster: kafka-dc
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 1
    cleanup.policy: compact, delete
