apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: hello
  labels:
    strimzi.io/cluster: kafka-dc
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 86400000
    cleanup.policy: compact, delete
