apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: topic04
  labels:
    strimzi.io/cluster: kafka-dc
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 25930000
    cleanup.policy: compact, delete
