apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: user1
  labels:
    strimzi.io/cluster: kafka-dc
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # access to kafka topic [All]
      - resource:
          type: topic
          name: aaf-master-currency
          patternType: literal
        operation: All
        host: "*"
      - resource:
          type: topic
          name: aaf-master-bank
          patternType: literal
        operation: All
        host: "*"
      - resource:
          type: topic
          name: test2
          patternType: literal
        operation: All
        host: "*"
      # access to kafka group [All]
      - resource:
          type: group
          name: group-test
          patternType: literal
        operation: All
        host: "*"
