apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: kanomnutt-topic
  labels:
    strimzi.io/cluster: kafka-dc
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 86400000
    cleanup.policy: compact, delete
    compression.type: zstd
    
